Repository scorelab/Codelabz, pull requests merged in 2022-10, with the labels that each got.

#244 Fixed typos in readme.md
  README.md
Labels: duplicate

#458 Link to user settings on profile page
  src/components/ProfileBanner/profile/ProfileCardOne/index.js
Labels: review needed, hacktoberfest-accepted

#466 updated local-firebase-emulators-import-export.md
  local-firebase-emulators-import-export.md
Labels: review needed, hacktoberfest-accepted

#463 Added Community in README.md
  README.md
Labels: review needed, hacktoberfest-accepted

#471 added input fields for organisation social media handles
  src/components/Organization/pages/General.js
Labels: review needed, hacktoberfest-accepted

#479 Add Organization Delete
  src/components/Organization/OrgInfoCard/orgInfoCard.js
  src/components/Organization/OrgUsers/OrgDelete.js
  src/components/Organization/OrgUsers/OrgDeleteModal.js
  src/store/actions/actionTypes.js
  src/store/actions/orgActions.js
Labels: review needed, hacktoberfest-accepted

#476 adding social media links in organization about page
  src/components/Organization/Orgsocial/index.js
  src/components/Organization/ViewOrganization/About.js
  src/components/Organization/pages/General.js
Labels: review needed, hacktoberfest-accepted

#481 #478 Align navbar menu
  src/components/NavBar/new/MainNavbar/RightMenu.js
Labels: review needed, hacktoberfest-accepted

#480 #453-implement-connect-social-media-buttons
  functions/auth.js
  src/components/Profile/ConnectSocials/index.js
  src/components/Profile/ConnectSocials/styles.js
Labels: hactoberfest, review needed, hacktoberfest-accepted

#482 added users and organizations
  README.md
  testdata/auth_export/accounts.json
  testdata/database_export/codelabz-eb407-default-rtdb.json
  testdata/database_export/codelabz-eb407.json
  testdata/firebase-export-metadata.json
  testdata/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  testdata/firestore_export/all_namespaces/all_kinds/output-0
  testdata/firestore_export/firestore_export.overall_export_metadata
Labels: hactoberfest, review needed, hacktoberfest-accepted

#484 Searchbar instead of dropdown for user country textfield
  src/components/Dashboard/index.js
  src/css/Searchbar/searchbar.css
Labels: hactoberfest, review needed
